=== officefloor/OfficeFloor/officefloor/trunk/officexml/src/schema/TreeXmlMarshaller.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *  Office Floor, Application Server
 *  Copyright (C) 2006 Daniel Sagenschneider
 *
 *  This program is free software; you can redistribute it and/or modify it under the terms 
 *  of the GNU General Public License as published by the Free Software Foundation; either 
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 *  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with this program; 
 *  if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
 *  MA 02111-1307 USA
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="marshall">
		<xs:annotation>
			<xs:documentation>Root mapping Object to XML</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attributes" minOccurs="0"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="value"/>
					<xs:element ref="object"/>
					<xs:element ref="type"/>
					<xs:element ref="collection"/>
					<xs:element ref="reference"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="element" type="xs:string" use="optional"/>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="attributes">
		<xs:annotation>
			<xs:documentation>Attributes for a particular object</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="attribute"/>
				<xs:element ref="traverse"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute">
		<xs:annotation>
			<xs:documentation>Mapping of an object value to an Attribute</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="attribute" type="xs:string" use="required"/>
			<xs:attribute name="method" type="xs:string" use="required"/>
			<xs:attribute name="isUseRaw" type="xs:boolean" use="optional" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="traverse">
		<xs:annotation>
			<xs:documentation>Obtains an object from the source object to specify attributes from</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="attribute"/>
				<xs:element ref="traverse"/>
			</xs:choice>
			<xs:attribute name="method" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="value">
		<xs:annotation>
			<xs:documentation>Mapping of an object value to a Value (ie &lt;element&gt;value&lt;/element&gt;)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="element" type="xs:string" use="required"/>
			<xs:attribute name="method" type="xs:string" use="required"/>
			<xs:attribute name="isUseRaw" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="object">
		<xs:annotation>
			<xs:documentation>Mapping of an object to XML</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attributes" minOccurs="0"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="value"/>
					<xs:element ref="object"/>
					<xs:element ref="type"/>
					<xs:element ref="collection"/>
					<xs:element ref="reference"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="method" type="xs:string" use="required"/>
			<xs:attribute name="element" type="xs:string" use="optional"/>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="type">
		<xs:annotation>
			<xs:documentation>Mapping based on type to XML</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="item"/>
			</xs:sequence>
			<xs:attribute name="method" type="xs:string" use="required"/>
			<xs:attribute name="element" type="xs:string" use="optional"/>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="collection">
		<xs:annotation>
			<xs:documentation>Mapping of a collection of objects to XML</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="item"/>
			</xs:sequence>
			<xs:attribute name="method" type="xs:string" use="required"/>
			<xs:attribute name="element" type="xs:string" use="optional"/>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="item">
		<xs:annotation>
			<xs:documentation>Mapping of a particular type of object to XML</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attributes" minOccurs="0"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="value"/>
					<xs:element ref="object"/>
					<xs:element ref="type"/>
					<xs:element ref="collection"/>
					<xs:element ref="reference"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="element" type="xs:string" use="optional"/>
			<xs:attribute name="id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="reference">
		<xs:annotation>
			<xs:documentation>Mapping by utilising another mapping (ie by reference).  Mainly used for recursion.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="method" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== officefloor/OfficeFloor/officefloor/trunk/officemodel/src/main/resources/net/officefloor/model/officefloor/MarshallConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<marshall xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../plugin/xml/src/schema/TreeXmlMarshaller.xsd" type="net.officefloor.model.officefloor.OfficeFloorModel" element="office-floor">
	<!-- MANAGED OBJECTS -->
	<collection method="getManagedObjectSources" element="managed-object-sources">
		<item type="net.officefloor.model.officefloor.ManagedObjectSourceModel" element="managed-object-source">
			<attributes>
				<attribute method="getId" attribute="id"/>
				<attribute method="getSource" attribute="source"/>
			</attributes>
			<object method="getManagingOffice" element="managing-office">
				<attributes>
					<attribute method="getManagingOfficeName" attribute="name"/>
				</attributes>
			</object>
			<collection method="getProperties" element="properties">
				<item type="net.officefloor.model.officefloor.PropertyModel" element="property">
					<attributes>
						<attribute method="getName" attribute="name"/>
						<attribute method="getValue" attribute="value"/>
					</attributes>
				</item>
			</collection>
		</item>
	</collection>
	<!-- TEAMS -->
	<collection method="getTeams" element="team-instances">
		<item type="net.officefloor.model.officefloor.TeamModel" element="team-instance">
			<attributes>
				<attribute method="getId" attribute="id"/>
				<attribute method="getTeamFactory" attribute="team-factory"/>
			</attributes>
			<collection method="getProperties" element="properties">
				<item type="net.officefloor.model.officefloor.PropertyModel" element="property">
					<attributes>
						<attribute method="getName" attribute="name"/>
						<attribute method="getValue" attribute="value"/>
					</attributes>
				</item>
			</collection>
		</item>
	</collection>
	<!-- OFFICES -->
	<collection method="getOffices" element="offices">
		<item type="net.officefloor.model.officefloor.OfficeFloorOfficeModel" element="office">
			<attributes>
				<attribute method="getId" attribute="id"/>
				<attribute method="getX" attribute="x"/>
				<attribute method="getY" attribute="y"/>
			</attributes>
			<collection method="getManagedObjects" element="managed-objects">
				<item type="net.officefloor.model.officefloor.OfficeManagedObjectModel" element="managed-object">
					<attributes>
						<attribute method="getManagedObjectName" attribute="name"/>
						<attribute method="getScope" attribute="scope"/>
					</attributes>
					<object method="getManagedObjectSource" element="managed-object-source">
						<attributes>
							<attribute method="getManagedObjectSourceId" attribute="id"/>
						</attributes>
					</object>
				</item>
			</collection>
			<collection method="getTeams" element="teams">
				<item type="net.officefloor.model.officefloor.OfficeTeamModel" element="team">
					<attributes>
						<attribute method="getTeamName" attribute="name"/>
					</attributes>
					<object method="getTeam" element="team-instance">
						<attributes>
							<attribute method="getTeamId" attribute="id"/>
						</attributes>
					</object>
				</item>
			</collection>
		</item>
	</collection>
</marshall>

=== officefloor/OfficeFloor/officefloor/trunk/officemodel/src/main/resources/net/officefloor/model/room/MarshallConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<marshall xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="..\..\..\..\..\..\..\..\src\schema\TreeXmlMarshaller.xsd"
	type="net.officefloor.model.room.RoomModel" element="room">
	<!-- EXTERNAL MANAGED OBJECTS -->
	<collection method="getExternalManagedObjects"
		element="external-managed-objects">
		<item
			type="net.officefloor.model.room.ExternalManagedObjectModel"
			element="external-managed-object">
			<attributes>
				<attribute method="getName" attribute="name" />
				<attribute method="getObjectType"
					attribute="object-type" />
			</attributes>
		</item>
	</collection>
	<!-- EXTERNAL FLOWS -->
	<collection method="getExternalFlows" element="external-flows">
		<item type="net.officefloor.model.room.ExternalFlowModel"
			element="external-flow">
			<attributes>
				<attribute method="getName" attribute="name" />
			</attributes>
		</item>
	</collection>
	<!-- EXTERNAL ESCALATIONS -->
	<collection method="getExternalEscalations"
		element="external-escalations">
		<item type="net.officefloor.model.room.ExternalEscalationModel"
			element="external-escalation">
			<attributes>
				<attribute method="getName" attribute="name" />
				<attribute method="getEscalationType"
					attribute="escalation-type" />
			</attributes>
		</item>
	</collection>
	<!-- SUB ROOMS -->
	<collection method="getSubRooms" element="sub-rooms">
		<item type="net.officefloor.model.room.SubRoomModel"
			element="sub-room">
			<attributes>
				<attribute method="getId" attribute="id" />
				<attribute method="getDesk" attribute="desk" />
				<attribute method="getRoom" attribute="room" />
				<attribute method="getX" attribute="x" />
				<attribute method="getY" attribute="y" />
			</attributes>
			<collection method="getInputFlows" element="input-flows">
				<item
					type="net.officefloor.model.room.SubRoomInputFlowModel"
					element="input-flow">
					<attributes>
						<attribute method="getName" attribute="name" />
						<attribute method="getIsPublic"
							attribute="public" />
					</attributes>
				</item>
			</collection>
			<collection method="getOutputFlows"
				element="output-flows">
				<item
					type="net.officefloor.model.room.SubRoomOutputFlowModel"
					element="output-flow">
					<attributes>
						<attribute method="getName" attribute="name" />
					</attributes>
					<object method="getInput" element="input">
						<attributes>
							<attribute method="getSubRoomName"
								attribute="sub-room" />
							<attribute method="getInputFlowName"
								attribute="name" />
						</attributes>
					</object>
					<object method="getExternalFlow"
						element="external-flow">
						<attributes>
							<attribute method="getExternalFlowName"
								attribute="name" />
						</attributes>
					</object>
				</item>
			</collection>
			<collection method="getManagedObjects"
				element="managed-objects">
				<item
					type="net.officefloor.model.room.SubRoomManagedObjectModel"
					element="managed-object">
					<attributes>
						<attribute method="getName" attribute="name" />
						<attribute method="getObjectType"
							attribute="object-type" />
					</attributes>
					<object method="getExternalManagedObject"
						element="external-managed-object">
						<attributes>
							<attribute method="getName"
								attribute="name" />
						</attributes>
					</object>
				</item>
			</collection>
			<collection method="getEscalations" element="escalations">
				<item
					type="net.officefloor.model.room.SubRoomEscalationModel"
					element="escalation">
					<attributes>
						<attribute method="getName" attribute="name" />
						<attribute method="getEscalationType"
							attribute="escalation-type" />
					</attributes>
					<object method="getInputFlow" element="input">
						<attributes>
							<attribute method="getSubRoomName"
								attribute="sub-room" />
							<attribute method="getInputFlowName"
								attribute="name" />
						</attributes>
					</object>
					<object method="getExternalEscalation"
						element="external-escalation">
						<attributes>
							<attribute method="getName"
								attribute="name" />
						</attributes>
					</object>
				</item>
			</collection>
		</item>
	</collection>
</marshall>
